### ISSUE TITLE
Lock Timer

### ISSUE THREAD

**Issue by eorroe** [MaKleSoft/padlock#47] opened 2016-08-09 21:05 UTC
When switching apps trying to login I have to keep inputing my master password which is annoying, there should be a timer/delay for when it ask me for that again.

**Comment by MaKleSoft** [comment] 2016-08-10 08:45
Duplicate of https://github.com/MaKleSoft/padlock/issues/37

@eorroe You'll be happy to hear that this will be in the next release!

**Closed by MaKleSoft** 2016-08-10 08:45 UTC
