### ISSUE TITLE
Let (mobile) apps sync with custom server instance

### ISSUE THREAD

**Issue by moritzheiber** [MaKleSoft/padlock#16] opened 2015-10-08 18:49 UTC
Right now, Padlock is able to sync with cloud.padlock.io, which is great, however, I would love to be able to run my own instance of the server and let the (mobile) apps (iOS/Android/possible stand-alone application to be developed) sync with it instead of trusting a third party with my password/sensitive information.

So there'd need to be a choice when setting up sync, i.e. entering a custom URL etc.

**Comment by dploeger** [comment] 2015-10-09 21:24
I'm looking into this, but I guess, the CSP set up in the index.html could be the problem here.

There, "AJAX-requests" (to summarize the different methods) are limited to the Padlock-Cloud, which is hardcoded. This way, the app cannot be tricked into something else.

We have to check, if it's possible to change that. Changing the CSP to a wildcard doesn't make much sense to me as we're in a high-security-context here.

**Comment by MaKleSoft** [comment] 2015-10-10 02:51
@dploeger This is a good analysis of the problem. Thinking about it, there is really no way to do this without relaxing the CSP, which is not something I'm keen to do.

**Comment by dploeger** [comment] 2015-10-10 09:25
@MaKleSoft Yes, I agree with you on that point, but this a major feature in my opinion! People mostly dislike the cloud-portion of the several existing password managers, as they cannot be sure, that the cloud is really secured - although sometimes the public cloud is more secure than their private ones. ;-)

**Comment by moritzheiber** [comment] 2015-10-10 09:26
I absolutely agree. Unfortunately, as @MaKleSoft mentioned, I don't see a way around the CSP :disappointed:

**Comment by dploeger** [comment] 2015-10-10 09:27
Perhaps at least restricting the CSP to https connections?

Another possibility would be a device-local proxy to only route to the configured server. Is this possible with the development framework?

**Comment by moritzheiber** [comment] 2015-10-10 09:28
Both of these suggestions actually sound sort of promising :smiley:

**Comment by MaKleSoft** [comment] 2015-10-10 09:39
Thanks for the suggestions! Let me think about this for a bit.

**Comment by dploeger** [comment] 2015-10-10 21:18
Let me ask, what attack vector we're preventing with this.

I guess it would be a malicious app rerouting the synchronisation-traffic to another server to intercept the (encrypted) password data.

If that's the vector, the CSP wouldn't be secure enough, because that app would need to change the padlock app's content and set the destination server and if it would have that possibility, it could simply overwrite the CSP.

And IF it could do something like that it could as well simply sniff the traffic or poison the device's DNS cache to route the data to its server.

Or am I misinterpreting the concept here?

**Comment by MaKleSoft** [comment] 2015-10-11 01:56
> I guess it would be a malicious app rerouting the synchronisation-traffic to another server to intercept the (encrypted) password data.

That's not quite correct. The `connect-src` directive restricts **all** Ajax requests to `cloud.padlock.io`, not just synchronisation traffic. An attacker intercepting synchronisation traffic would in theory not be a problem since all of the sensitive data is encrypted. Instead, this protects against malicious code trying to communicate with a source controlled by the attacker. Of course, for this to happen the attacker would first have to find a way to inject malicious code into the app which we should theoretically be protected against by the `script-src` restriction. It certainly is a redundant security measure which is not necessarily a bad thing.

Another way to handle this is route traffic to third-party cloud instances through cloud.padlock.io and give people a way to register 'trusted sources'. This would raise additional challenges however...

**Comment by dploeger** [comment] 2015-10-11 06:23
Are there more AJAX requests beside the synchronisation traffic?

Yes, I thought about that proxy solution as well, but this would still leave some doubt on the customer side. The mail apps, that route authentication traffic over a cloud host (for push purposes mostly), also always leave a bitter taste - at least for commercial users.

I was thinking about a device-local proxy, that could be configured by the app, but that would obviously just circumvent the CSP and open up the attack vector we're trying to mitigate by using the CSP.

Another way would be to exchange the app sources, but that isn't allowed on iOS.

So, yes, I think the only way would be to open up the CSP. :/

**Comment by moritzheiber** [comment] 2015-10-11 06:49
Proxying requests through `cloud.padlock.io` would take away the security benefit you'd expect to carry through when using a custom instance. You're essentially a man-in-the-middle between a custom instance and the end user. That doesn't sound like a viable solution to me.

The local proxy (which I know is possible within browser frameworks, but I doubt is going to be possible on e.g. iOS) and relaxing the CSP so far are the only solutions I see fit to address this feature request.

**Comment by MaKleSoft** [comment] 2015-10-11 09:22
You're absolutely right about proxying through cloud.padlock.io. Don't know why I didn't think of that. I know it's possible to run a local web server in iOS but that would open an entire new class of attack vectors. So relaxing the CSP is really the only practical solution that I can see. Let me try to think of a strong reason not to go this direction...

**Comment by dploeger** [comment] 2015-10-11 09:44
Thanks about your prompt support and insight here, Martin!

**Comment by s4astliv** [comment] 2015-10-11 14:59
Just few more points to add. Possibility to use customer port number and possibility to automatically accept self signed certificates in case of SSL. Thank you for looking into this feature request. This is the only thing that keeps me from using the app.

**Comment by MaKleSoft** [comment] 2015-10-12 03:44
> This is the only thing that keeps me from using the app.

@s4astliv Just out of curiosity: Would you use the app if it supported synchronising with your Dropbox or Google Drive account instead?

**Comment by s4astliv** [comment] 2015-10-12 05:43
There are many password apps that support only dropbox or google drive, Martin. I wouldn't use them.

By the way, the server instance is written in Go language. I think it is possible to write PHP and MySQL version of server and run in Apache for easier setup on the server side.

**Comment by moritzheiber** [comment] 2015-10-12 06:14
I would specifically use this app because it supports sync without a third party. Why would I trust Google/Dropbox with my password data but I won't trust padlock.io? It's the same argument, essentially, and why I created this issue.

PS: I don't see the advantage of reimplementing a golang server in PHP/MySQL. IMHO it adds more moving parts, which I don't want to have within my trusted environment. And it's already dead simple to deploy a golang binary :)

**Comment by MaKleSoft** [comment] 2015-10-12 07:30
@s4astliv @moritzheiber Thanks guys, this is actually extremely valuable feedback. I will definitely try and back it as simple as possible to deploy your own Padlock Cloud instance. As for the implementation language: PHP won't happen, but I can see that Golang is not necessarily the best choice if we want people to easily deploy and contribute to it. I was thinking about maybe porting it over to Node.js at some point.

**Comment by moritzheiber** [comment] 2015-10-12 07:35
Don't want to start a turf war here, but I expressively think Golang is exactly the right language for very easy deployments.

It's a single binary, it works on pretty much any architecture, you just need to download and run it. What's easier than that? :)

Node.js would require me to at least install a package manager and probably a lot of different packages as well. I just wouldn't see the advantage.

If you want my 2c, stick with golang on the server side.

**Comment by MaKleSoft** [comment] 2015-10-12 07:39
@moritzheiber I absolutely hear you! I think there is some definite advantages to using a package manager though like easier updates, dependency management etc. There are other priorities right now anyway so for now we'll definitely stick with Golang.

**Comment by moritzheiber** [comment] 2015-10-12 07:46
That's merely an argument in favor of package managers, not languages.

Go even has package management backend right into its core, although a little inferior than some of the available alternatives (gom, nut). I don't necessarily see that as an argument in favor of node.js :)

But as you said, let's talk about this again once the decision has to be taken.

**Comment by s4astliv** [comment] 2015-10-12 13:46
Whatever language you choose for the server, make sure it is possible to easy make a backup of database and restore it. What db is used with Go lang deployment?

**Comment by MaKleSoft** [comment] 2015-10-12 16:02
We're using a Golang implementation of LevelDB: https://github.com/syndtr/goleveldb

**Comment by s4astliv** [comment] 2015-10-12 21:16
Another thought on it. I don't think it is possible to run Go on web hosting, unless you rent the whole server. It is possible to run Node.js on web server with some tweaking though. My point is that implementation of languages like Go cuts off a huge bunch of users who don't have a server to operate, but have and can use their hosting provider instead. I would trust my provider more than Google Drive, Dropbox or Padlock Cloud.

P.S. For a record, I have access to the server and can use Go language with no issues.

**Comment by moritzheiber** [comment] 2015-10-12 22:03
There are literally dozens of available service providers eager and ready to run any Golang based application you throw at them. Google App Engine, Heroku or Pivotal, just to name a few. Add the popular Docker hosting solutions on top (which Go is ideal for given its signal binary no dependencies nature) and you have plenty of options to choose from.

Also, if your host runs PHP or Node.js it can run Go.

**Comment by s4astliv** [comment] 2015-10-13 10:03
Just confirmed with my hosting that they do not support running Go, unless you rent the whole server. Blacknight.ie

**Comment by cclafferty** [comment] 2015-10-22 09:35
@s4astliv do you really want to be running your Padlock Cloud on a shared server? I would have thought that the desire to run your own Padlock Cloud was based on an intention to increase your security and piece of mind? I wouldn't recommend a shared server for those things.

**Comment by s4astliv** [comment] 2015-10-22 09:51
@cclafferty agree, I would not use shared hosting, as said before I have access to the server and can use Go language with no issues. Just thinking about others.

**Comment by MaKleSoft** [comment] 2016-08-04 08:25
I think we can close this one. Entering a custom server address will be possible starting with the next release. I'm also working on simplifying the process of building and deploying your own padlock cloud instance. Stay tuned!

**Closed by MaKleSoft** 2016-08-04 08:25 UTC

**Comment by moritzheiber** [comment] 2016-08-04 08:40
That's great news! Cheers!

PS: You can auto-close issues through commits/PRs and even releases (if your release is happening to the default branch):

https://help.github.com/articles/closing-issues-via-commit-messages/
https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by MaKleSoft** [comment] 2016-08-04 08:45
@moritzheiber Yeah, I know, but at the time I had forgotten about this issue (I'm keeping a separate Trello board to keep track of things).

**Comment by dploeger** [comment] 2016-10-10 21:23
Just created my own instance without any problems. Thanks!
