### ISSUE TITLE
Integrate support for TouchId on macos and ios devices

### ISSUE THREAD

**Issue by quux** [MaKleSoft/padlock#166] opened 2018-03-21 19:50 UTC
Allow user to unlock Padlock using TouchId so that he does not have to type in his password.

A Cordova plugin is available for TouchId: https://github.com/leecrossley/cordova-plugin-touchid

**Comment by MaKleSoft** [comment] 2018-03-22 13:16
Duplicate of https://github.com/MaKleSoft/padlock/issues/21

Just a short note on this: We've been very hesitant in the past about adding support for TouchID/FaceID due to various security and UX caveats. However, since this is by far the most requested feature (and for a lot of people the one thing that keeps them from using the app) we are starting to reconsider our decision. No promises or timelines yet, but it's starting to look more likely. Stay tuned...

**Closed by MaKleSoft** 2018-03-22 13:16 UTC
