### ISSUE TITLE
Ability to restore last value / history

### ISSUE THREAD

**Issue by pwasiewicz** [MaKleSoft/padlock#163] opened 2018-03-15 08:30 UTC
Situation occured yesterday:
On my mobile phone (Android) I have acciendetialy removed field content (whole content of field is automatically selected on focus). I think that problem comes from keyboard, that is automatically showing up and it is easy to make mistake and press any button by accident. This + auto content select on focus = disaster. I was not able to restore original value :( 
On desktop, maybe CTRL+Z would help, but there is no such a way to try on mobile.
Ideas to solve this issue:
- Button to cancel all changes (for all entries) made since entry entrance
- Button to restore field value changes made since entry entrance
- History of field changes (f.e. storing changes made in last 30 days).
- Allow editing value only after clicking dedicated button-per-field (by default, field is readonly). This should work only while editing entry, when entry is first created - all field could be editable for convenience.

What do you think about it?

**Comment by MaKleSoft** [comment] 2018-03-15 13:52
> Button to cancel all changes (for all entries) made since entry entrance

Something like this exists already. If you click the the `x` icon on the right while editing, your changes will be discarded. 
![image](https://user-images.githubusercontent.com/1270940/37466611-f28e846a-283c-11e8-9df4-70165fafa7ea.png)

We're actually working on redesigning the user experience for interacting with fields. So we're probably gonna go more in the direction of your last suggestion:

> Allow editing value only after clicking dedicated button-per-field (by default, field is readonly). This should work only while editing entry, when entry is first created - all field could be editable for convenience.

Editing / interacting with fields turns out to be one of the harder challenges when it comes to ux design, especially if you're trying to find a unified design for desktop and mobile. We're trying to make the user experience as frictionless as possible for the most common actions while still allowing for advanced functionality (there is more stuff coming in the future). One important thing that we've been trying to identify but that we don't have sufficient data on yet is the priority of actions as in how often users perform them and how easily they should be accessible. Right now my guess is something like this (For existing fields):

1. Copy to clipboard
2. Unmask / Display
3. Edit value
4. Edit value using password generator
5. Delete Field

@pwasiewicz Is that somewhat in line with your experience?

**Comment by pwasiewicz** [comment] 2018-03-15 14:20
Hmm, thank you for clarification.
The button you have marked looks like... delete button, so I have not ever pressed it (I was afraid of lossing field). Good to know!
But indeed, I think that the last suggestion should be have the best safety/usability ratio.

The most used actions for me is

1. Copy to clipboard. No need to comment why :)
2. Edit value using password generator. Some passwords needs to be changed after some period of time, most of them (in my case) is randomly generated guid. So it would be extremely useful to generate new-one somehow quickly and safely. 

Next:

3. Unmask / Display. Like I have mentioned earlier, good passwords can be hard to remember so "Copy to clipboard" is enough for me. This can me useful in cases, where you need to rewrite password to external device / place etc. only.
4. Edit value (only some typos are edited, does someone edits password? :) )
5. Delete field. I think that `Delete entry` is used more often.

**Comment by MaKleSoft** [comment] 2018-03-22 13:18
@pwasiewicz Thanks, your feedback is immensely helpful as always! I'm closing this now, but I'll keep your feedback in mind when designing the new UX!

**Closed by MaKleSoft** 2018-03-22 13:18 UTC

**Comment by pwasiewicz** [comment] 2018-11-16 21:43
@MaKleSoft I think that this issue can be reopen. Consider scenario, when I need update password due to site policy.
1. Site requested for old password and new password.
2. I have opened Padlock, copied password and put into "old password" field. 
3. Then generated new password in padlock, saved and copied to "new password" field.
4. An error occured while saving form, need to re-enter values again.
5. **Old password is lost in Padlock**.  There is no possibility to recover password after hiting "save" on edit popup. Padlock instantly synchronized across all of devices :(

Maybe f.e. last up to 3 last changes should be somehow stored?

**Comment by pwasiewicz** [comment] 2018-11-16 22:44
> This is a pain point that has come up in my use quite frequently too. I usually get around it right now by creating another field under the entry for the new password until I'm sure I'm done with the old one.

@forstermatth yeah you are right. It is a solution, but I think that the UX suffers in that case. 
I believe that in the most of cases nothing goes wrong (but if sth go wrong - it is a disaster), so creating new field everytime I want to update password is overwhelming in my opinion. That is why short "history" of record could be convenient and can save a day. Especially we can override field that is not a password. necessarily.

**Comment by forstermatth** [comment] 2018-11-16 22:53
@pwasiewicz I definitely agree, I think an average user would probably have to be stung (like yourself, and I) a couple times before thinking up a solution. There are two workarounds really in the current UI, without using an external record;

1. The first that I described above.
2. To not save the newly generated password onto the field until the change has been completed - but this requires you to leave the field in an inconsistent state for a minute or so until the change has been confirmed. This also seems to work ok, as the 'new' password value doesn't matter until the change is confirmed.

Both of these aren't really obvious to a user who is not thinking about how this action can affect their data, so it does require some thought to see if we can't make it easier. It's probably also worth pointing out that other password managers often have a _restore last x_ ability.
